# Generated by Django 5.0.3 on 2024-04-24 19:13

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstore', '0002_post_sumario_alter_post_autor_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='sumario',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
